In [2]:
import pandas as pd
df= pd.read_csv("data.csv")
df

     Duration  Pulse  Maxpulse  Calories
0        60.0  110.0     130.0     409.1
1        60.0  117.0     145.0     479.0
2        60.0  103.0     135.0     340.0
3        45.0  109.0     175.0     282.4
4        45.0  117.0     148.0     406.0
..        ...    ...       ...       ...
164      60.0  105.0     140.0     290.8
165      60.0  110.0     145.0     300.0
166      60.0  115.0     145.0       NaN
167      75.0  120.0     150.0       NaN
168      75.0  125.0     150.0       NaN

[169 rows x 4 columns]

In [4]:
df = df[["Pulse",'Calories']]
df

     Pulse  Calories
0    110.0     409.1
1    117.0     479.0
2    103.0     340.0
3    109.0     282.4
4    117.0     406.0
..     ...       ...
164  105.0     290.8
165  110.0     300.0
166  115.0       NaN
167  120.0       NaN
168  125.0       NaN

[169 rows x 2 columns]

## Applying Normalization : Minmax Scalling

In [5]:
from sklearn.preprocessing import MinMaxScaler

In [6]:
scaler = MinMaxScaler()

In [7]:
scaler_df = scaler.fit_transform(df)
scaler_df

array([[3.79746835e-01, 1.98221093e-01],
       [4.68354430e-01, 2.36837744e-01],
       [2.91139241e-01, 1.60046406e-01],
       [3.67088608e-01, 1.28224960e-01],
       [4.68354430e-01, 1.96508480e-01],
       [2.78481013e-01, 1.37948180e-01],
       [3.79746835e-01, 1.78829899e-01],
       [3.03797468e-01, 1.12148500e-01],
       [3.67088608e-01, 7.99955804e-02],
       [2.27848101e-01, 1.20822054e-01],
       [2.91139241e-01, 1.54135131e-01],
       [2.53164557e-01, 1.10712115e-01],
       [3.29113924e-01, 1.62974421e-01],
       [3.03797468e-01, 1.81757914e-01],
       [2.27848101e-01, 1.24136788e-01],
       [2.27848101e-01, 9.10999392e-02],
       [2.53164557e-01, 1.37948180e-01],
       [1.26582278e-01,            nan],
       [2.91139241e-01, 1.50654660e-01],
       [2.15189873e-01, 1.06458207e-01],
       [3.54430380e-01, 1.73415833e-01],
       [2.53164557e-01, 1.28003978e-01],
       [6.32911392e-01, 1.37948180e-01],
       [3.16455696e-01, 1.08115574e-01],
       [2.78481013e-01, 1.57007900e-01],
       [2.53164557e-01, 1.10325396e-01],
       [1.51898734e-01, 1.05353295e-01],
       [2.91139241e-01,            nan],
       [2.53164557e-01, 1.26899066e-01],
       [2.78481013e-01, 1.82310370e-01],
       [1.51898734e-01, 1.06458207e-01],
       [1.26582278e-01, 7.17087454e-02],
       [2.65822785e-01, 1.37395724e-01],
       [1.64556962e-01, 9.54090934e-02],
       [3.41772152e-01, 1.71647975e-01],
       [4.30379747e-01, 2.01480581e-01],
       [2.78481013e-01, 1.37948180e-01],
       [2.53164557e-01, 1.37948180e-01],
       [2.53164557e-01, 1.37948180e-01],
       [3.03797468e-01, 1.19164687e-01],
       [1.26582278e-01, 7.17087454e-02],
       [           nan,            nan],
       [2.53164557e-01, 1.54190376e-01],
       [3.92405063e-01, 1.93193746e-01],
       [3.92405063e-01, 1.91536379e-01],
       [2.40506329e-01, 1.23031877e-01],
       [3.67088608e-01, 1.86343296e-01],
       [3.92405063e-01, 1.37948180e-01],
       [3.54430380e-01, 1.36843268e-01],
       [3.92405063e-01, 1.91867853e-01],
       [3.41772152e-01, 1.82255124e-01],
       [5.44303797e-01, 3.27495718e-01],
       [3.29113924e-01, 1.17507320e-01],
       [4.81012658e-01, 2.40704933e-01],
       [7.08860759e-01, 1.03695928e-01],
       [5.18987342e-01, 2.21203248e-01],
       [4.81012658e-01, 2.00375670e-01],
       [4.43037975e-01, 1.40710458e-01],
       [9.24050633e-01, 9.72874427e-02],
       [5.44303797e-01, 1.49549749e-01],
       [3.54430380e-01, 7.32390476e-01],
       [3.79746835e-01, 5.43671620e-01],
       [3.67088608e-01, 4.43456163e-01],
       [4.81012658e-01, 1.60598862e-01],
       [3.79746835e-01, 4.48041545e-02],
       [1.26582278e-01, 4.14396995e-01],
       [3.16455696e-01, 4.54726258e-01],
       [3.41772152e-01, 4.23015303e-01],
       [3.29113924e-01, 3.32025855e-02],
       [3.54430380e-01, 8.01005469e-01],
       [           nan,            nan],
       [3.67088608e-01, 1.86343296e-01],
       [2.53164557e-01, 3.58930446e-01],
       [2.15189873e-01, 4.98812220e-01],
       [4.30379747e-01, 1.40158002e-01],
       [2.27848101e-01, 2.83354511e-01],
       [3.16455696e-01, 1.10877852e-01],
       [3.79746835e-01, 1.37948180e-01],
       [2.53164557e-01, 2.48660295e-01],
       [2.53164557e-01, 9.27407326e-01],
       [1.00000000e+00, 1.48555328e-01],
       [8.73417722e-01, 1.62256229e-01],
       [2.91139241e-01, 5.56875311e-02],
       [           nan, 2.48439313e-01],
       [           nan, 9.66797415e-02],
       [           nan, 1.37948180e-01],
       [           nan, 1.01486106e-01],
       [2.53164557e-01, 5.24722391e-01],
       [6.20253165e-01, 1.05905751e-01],
       [3.79746835e-02, 0.00000000e+00],
       [2.65822785e-01, 3.03740125e-01],
       [3.41772152e-01,            nan],
       [1.26582278e-01, 3.03850616e-02],
       [0.00000000e+00, 1.10491133e-04],
       [8.86075949e-01, 4.25943318e-02],
       [           nan,            nan],
       [           nan,            nan],
       [           nan,            nan],
       [3.67088608e-01, 7.61836363e-02],
       [1.64556962e-01, 3.05949948e-01],
       [1.89873418e-01, 1.51372852e-02],
       [1.26582278e-01, 2.48439313e-01],
       [1.26582278e-01, 2.48439313e-01],
       [1.26582278e-01, 2.48660295e-01],
       [1.51898734e-01, 2.34241202e-02],
       [           nan, 4.07159825e-02],
       [           nan, 4.14341749e-01],
       [1.26582278e-01, 1.98331584e-02],
       [1.26582278e-01, 2.48605049e-01],
       [7.21518987e-01, 1.00000000e+00],
       [2.78481013e-01, 1.51870062e-01],
       [3.41772152e-01, 1.24136788e-01],
       [5.56962025e-01, 4.08264737e-02],
       [2.53164557e-01, 9.66797415e-02],
       [           nan, 1.75294183e-01],
       [3.54430380e-01, 1.66510138e-01],
       [4.55696203e-01, 2.16949340e-01],
       [2.15189873e-01, 1.25462682e-01],
       [3.16455696e-01,            nan],
       [2.91139241e-01, 1.56013480e-01],
       [4.05063291e-01, 7.93326336e-02],
       [2.53164557e-01, 2.78437655e-02],
       [4.93670886e-01, 1.58223303e-01],
       [3.41772152e-01, 1.62753439e-01],
       [3.92405063e-01, 1.75791393e-01],
       [2.27848101e-01, 1.21926965e-01],
       [2.15189873e-01, 1.24302525e-01],
       [3.67088608e-01, 1.83249544e-01],
       [2.40506329e-01, 2.29876802e-01],
       [           nan,            nan],
       [3.03797468e-01, 1.61427545e-01],
       [3.41772152e-01, 1.69714380e-01],
       [2.91139241e-01, 1.57284128e-01],
       [3.29113924e-01, 1.53140710e-01],
       [           nan, 1.59493951e-01],
       [7.08860759e-01, 7.66256008e-02],
       [           nan, 1.47726645e-01],
       [4.43037975e-01, 1.47892382e-01],
       [4.17721519e-01, 1.42367825e-01],
       [7.72151899e-01, 9.50776200e-02],
       [3.54430380e-01, 1.87669190e-01],
       [2.15189873e-01,            nan],
       [2.53164557e-01, 1.10546379e-01],
       [5.31645570e-01, 1.57505110e-01],
       [7.08860759e-01, 2.31976134e-01],
       [3.29113924e-01, 1.21816474e-01],
       [           nan,            nan],
       [           nan,            nan],
       [2.91139241e-01, 7.44157781e-02],
       [3.79746835e-01, 1.98386829e-01],
       [3.29113924e-01, 1.61703773e-01],
       [3.67088608e-01, 1.67338821e-01],
       [3.67088608e-01, 1.78829899e-01],
       [8.86075949e-01, 1.24578753e-01],
       [3.16455696e-01, 1.53416938e-01],
       [3.92405063e-01, 1.75791393e-01],
       [2.15189873e-01, 1.21595492e-01],
       [2.53164557e-01, 1.21595492e-01],
       [4.30379747e-01, 1.83691509e-01],
       [0.00000000e+00, 1.05298050e-01],
       [6.32911392e-02, 1.10546379e-01],
       [1.26582278e-01, 1.16070935e-01],
       [           nan, 1.21374510e-01],
       [2.53164557e-01, 1.27396276e-01],
       [3.16455696e-01, 1.32865588e-01],
       [3.79746835e-01, 1.37948180e-01],
       [4.43037975e-01,            nan],
       [5.06329114e-01,            nan],
       [5.69620253e-01,            nan]])

In [8]:
scaler_df = pd.DataFrame(data=scaler_df , columns=df.columns)
scaler_df

        Pulse  Calories
0    0.379747  0.198221
1    0.468354  0.236838
2    0.291139  0.160046
3    0.367089  0.128225
4    0.468354  0.196508
..        ...       ...
164  0.316456  0.132866
165  0.379747  0.137948
166  0.443038       NaN
167  0.506329       NaN
168  0.569620       NaN

[169 rows x 2 columns]

## Train Test Split

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x = df.drop("Pulse",axis = 1)
y = df['Pulse']

In [12]:
x_train,x_test,y_train,y_test = train_test_split(x,y ,test_size = 0.2,random_state = 42)

In [13]:
x_train.shape

(135, 1)

In [14]:
x_test.shape

(34, 1)

## Feature - Scalling : Normalization : Minmax Scaler

In [15]:
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [17]:
x_train_scaled

array([[8.63704057e-01],
       [1.59468636e-01],
       [1.72574016e-01],
       [1.19139811e-04],
       [8.26234586e-02],
       [1.74361113e-01],
       [3.27515339e-01],
       [1.89015309e-01],
       [1.13599809e-01],
       [1.31351641e-01],
       [1.59289927e-01],
       [           nan],
       [4.46833860e-01],
       [1.48746053e-01],
       [1.34032287e-01],
       [1.48746053e-01],
       [2.67885864e-01],
       [1.19199380e-01],
       [           nan],
       [1.19378090e-01],
       [4.56126765e-01],
       [1.69595520e-01],
       [1.92827783e-01],
       [           nan],
       [2.68124144e-01],
       [           nan],
       [1.48746053e-01],
       [           nan],
       [2.11890153e-01],
       [1.19199380e-01],
       [1.48150354e-01],
       [4.90319890e-01],
       [1.97593376e-01],
       [           nan],
       [1.66200036e-01],
       [1.63221540e-02],
       [1.79543695e-01],
       [2.13736820e-01],
       [1.31470781e-01],
       [1.35283255e-01],
       [4.83111932e-02],
       [2.06528862e-01],
       [8.55423840e-02],
       [1.36832072e-01],
       [7.73217371e-02],
       [           nan],
       [1.18961101e-01],
       [1.16578305e-01],
       [1.75492941e-01],
       [1.74956812e-01],
       [1.00000000e+00],
       [1.04247334e-01],
       [1.28492286e-01],
       [4.59283970e-02],
       [1.09429916e-01],
       [4.40221600e-02],
       [1.43265622e-01],
       [           nan],
       [1.48746053e-01],
       [2.47870376e-01],
       [5.86227438e-01],
       [5.37856675e-01],
       [1.02877226e-01],
       [1.98069935e-01],
       [1.89551439e-01],
       [1.82998749e-01],
       [4.78167630e-01],
       [           nan],
       [2.52576398e-02],
       [1.02519807e-01],
       [2.59546077e-01],
       [1.48746053e-01],
       [1.70608209e-01],
       [1.38261750e-01],
       [1.31113362e-01],
       [2.06886281e-01],
       [2.17251445e-01],
       [1.60183475e-01],
       [1.48746053e-01],
       [1.85083696e-01],
       [2.00929291e-01],
       [1.20926908e-01],
       [2.08315959e-01],
       [           nan],
       [8.02406624e-02],
       [1.63757670e-01],
       [           nan],
       [2.67885864e-01],
       [1.89551439e-01],
       [1.92827783e-01],
       [0.00000000e+00],
       [8.62572229e-02],
       [1.25156371e-01],
       [1.04247334e-01],
       [1.95984988e-01],
       [1.61255734e-01],
       [2.50134032e-01],
       [           nan],
       [3.87025675e-01],
       [           nan],
       [1.71978317e-01],
       [2.02358968e-01],
       [1.65425627e-01],
       [1.73169715e-01],
       [1.11812712e-01],
       [2.13855960e-02],
       [1.96521118e-01],
       [           nan],
       [1.04902603e-01],
       [1.47554655e-01],
       [1.14195508e-01],
       [1.38023471e-01],
       [1.51724549e-01],
       [1.37368202e-01],
       [           nan],
       [1.48746053e-01],
       [1.13540239e-01],
       [2.55376184e-01],
       [1.26705189e-01],
       [2.13915530e-01],
       [1.74063263e-01],
       [1.80437243e-01],
       [2.68124144e-01],
       [3.29898135e-01],
       [2.33931018e-01],
       [5.65794960e-01],
       [1.51128850e-01],
       [3.00232323e-02],
       [           nan],
       [1.86989933e-01],
       [2.00929291e-01],
       [4.46774290e-01],
       [1.33853577e-01],
       [3.27634479e-02],
       [2.67885864e-01]])

In [18]:
x_test_scaled

array([[0.15351165],
       [0.11479121],
       [0.16822541],
       [0.19658069],
       [0.1698338 ],
       [0.13087508],
       [0.14874605],
       [0.3531304 ],
       [0.04390302],
       [0.78971823],
       [0.09823077],
       [0.13111336],
       [0.16512778],
       [0.13266218],
       [0.03580151],
       [0.14874605],
       [0.16929767],
       [1.07827486],
       [0.30553404],
       [0.26806457],
       [0.11479121],
       [0.14874605],
       [0.07732174],
       [0.16244713],
       [0.17573122],
       [0.13027938],
       [0.06004646],
       [0.0821469 ],
       [0.1195568 ],
       [0.2385179 ],
       [0.16625961],
       [0.21606005],
       [0.13433014],
       [0.13385358]])

In [20]:
x_train_scaled = pd.DataFrame(data= x_train_scaled, columns=x_train.columns)
x_test_scaled = pd.DataFrame(data=x_test_scaled, columns=x_train.columns)

In [21]:
x_train_scaled

     Calories
0    0.863704
1    0.159469
2    0.172574
3    0.000119
4    0.082623
..        ...
130  0.200929
131  0.446774
132  0.133854
133  0.032763
134  0.267886

[135 rows x 1 columns]