In [1]:
import numpy as np
import pandas as pd

In [2]:
df =pd.read_csv('CAR DETAILS FROM CAR DEKHO.csv',usecols=['name','fuel','seller_type','transmission','owner'])
df.head()

                       name    fuel seller_type transmission         owner
0             Maruti 800 AC  Petrol  Individual       Manual   First Owner
1  Maruti Wagon R LXI Minor  Petrol  Individual       Manual   First Owner
2      Hyundai Verna 1.6 SX  Diesel  Individual       Manual   First Owner
3    Datsun RediGO T Option  Petrol  Individual       Manual   First Owner
4     Honda Amaze VX i-DTEC  Diesel  Individual       Manual  Second Owner

In [3]:
df.drop('name',axis=1,inplace=True)

In [4]:
df

        fuel seller_type transmission         owner
0     Petrol  Individual       Manual   First Owner
1     Petrol  Individual       Manual   First Owner
2     Diesel  Individual       Manual   First Owner
3     Petrol  Individual       Manual   First Owner
4     Diesel  Individual       Manual  Second Owner
...      ...         ...          ...           ...
4335  Diesel  Individual       Manual  Second Owner
4336  Diesel  Individual       Manual  Second Owner
4337  Petrol  Individual       Manual  Second Owner
4338  Diesel  Individual       Manual   First Owner
4339  Petrol  Individual       Manual   First Owner

[4340 rows x 4 columns]

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.drop('fuel',axis=1),df['fuel'], test_size=0.2, random_state=42)

In [8]:
X_train

     seller_type transmission         owner
227   Individual       Manual   First Owner
964   Individual       Manual   First Owner
2045  Individual       Manual  Second Owner
1025  Individual       Manual   First Owner
4242      Dealer       Manual   First Owner
...          ...          ...           ...
3444  Individual       Manual   First Owner
466   Individual       Manual   First Owner
3092      Dealer       Manual   First Owner
3772  Individual       Manual   First Owner
860   Individual       Manual   First Owner

[3472 rows x 3 columns]

## Using Scikitlearn

In [9]:
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder

## 1 Applying Label Encoder

In [10]:
le = LabelEncoder()
y_train_scaled = le.fit_transform(y_train)
y_test_scaled = le.transform(y_test)
y_train_scaled

array([1, 1, 4, ..., 1, 1, 4])

In [ ]:
Oe = OrdinalEncoder()
y_train_traf= Oe.fit_transform(y_train)
y_test_traf = Oe.transform(y_test)
y_train_traf

In [ ]:
X_train_traf